### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [hayakasa/docker-vagrant-template-rails#4]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`README.md`](https://github.com/hayakasa/docker-vagrant-template-rails/blob/05b52499f10406359dd7fcf54076a787551d599a/README.md). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by hayakasa** [comment]
@reitermarkus Thank you for your message. I just deleted that link.
